name = "bratgenerators"
compatibility_date = "2024-04-24"
workers_dev = true
main = ".vercel/output/static/_worker.js/index.js"
compatibility_flags = ["nodejs_compat"]

[build]
command = "next build && npx @cloudflare/next-on-pages"
cwd = "."

[site]
bucket = ".vercel/output/static"

[env.production]
workers_dev = true 